# -*- coding: utf-8 -*-
"""Linear Reg.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WHinZeYM5SEiU3pphQrkAY5Y04YZs5j6
"""

#import lib
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df=pd.read_csv('Crop_recommendation.csv')

df

df.shape

df.isnull().sum()

X=df.drop( ['temperature','humidity','rainfall','label'],axis=1)

y=df['label']

X

y

xdf = df.copy()
xdf

from sklearn.preprocessing import LabelEncoder 
labelencoder= LabelEncoder()

xdf['label_codes'] = labelencoder.fit_transform(xdf['label']) 
xdf

X = xdf.drop(['temperature','humidity','rainfall','label','label_codes'],axis = 1)

y = xdf['label_codes']

X

y

from sklearn.model_selection import train_test_split

Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.3)

from sklearn.linear_model import LinearRegression

reg=LinearRegression()

reg.fit(Xtrain, ytrain)

ytest

pred=reg.predict(Xtest)

pred

from sklearn.metrics import mean_squared_error

accuracy_train = []
accuracy_test = []
model_name = []

predict_linear_train = reg.predict(Xtrain)
MSE_linear_train = ( mean_squared_error(ytrain, predict_linear_train)  )

accuracy_linear_train = 100 - MSE_linear_train
print("Train Accuracy: ", accuracy_linear_train)

predict_linear_test = reg.predict(Xtest)
MSE_linear_test = ( mean_squared_error(ytest, predict_linear_test)  )
accuracy_linear_test = 100 - MSE_linear_test
print("Test Accuracy: ", accuracy_linear_test)

accuracy_train.append( accuracy_linear_train )
accuracy_test.append( accuracy_linear_test )
model_name.append('Linear Regression')

dftable = pd.DataFrame(columns={'accuracy_train', 'accuracy_test', 'model_name'})
dftable['accuracy_train'] = accuracy_train
dftable['accuracy_test'] = accuracy_test
dftable['model_name'] = model_name
dftable = dftable[['model_name', 'accuracy_train', 'accuracy_test']]
dftable


