# Generated by Django 4.1.2 on 2023-03-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uID', models.IntegerField()),
                ('uName', models.CharField(max_length=40)),
                ('uMail', models.EmailField(max_length=30)),
                ('uPhone', models.TextField(max_length=15)),
                ('uDOB', models.DateField()),
                ('uPassword', models.CharField(max_length=40)),
            ],
        ),
    ]
