# Generated by Django 4.1.7 on 2023-03-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uID',
        ),
        migrations.AlterField(
            model_name='user',
            name='uPhone',
            field=models.CharField(max_length=15),
        ),
    ]
