# Generated by Django 4.2 on 2023-04-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_prediction_k_alter_prediction_n_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='newp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField(max_length=40)),
                ('p', models.IntegerField(max_length=30)),
                ('ph', models.FloatField()),
                ('k', models.IntegerField(max_length=15)),
            ],
        ),
    ]
