# Generated by Django 4.2 on 2023-04-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_newp'),
    ]

    operations = [
        migrations.CreateModel(
            name='newprediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField(max_length=40)),
                ('p', models.IntegerField(max_length=30)),
                ('k', models.IntegerField(max_length=15)),
                ('ph', models.FloatField()),
                ('h', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='newp',
        ),
    ]
